export default {
  GET_EXPERIENCE_DETAILS: 'GET_EXPERIENCE_DETAILS',
  GET_EXPERIENCES: 'GET_EXPERIENCES',
  GET_CREATED_EXPERIENCES: 'GET_CREATED_EXPERIENCES',
  GET_HOST_BOOKED_DATES: 'GET_HOST_BOOKED_DATES',
  GET_USER_BOOKED_DATES: 'GET_USER_BOOKED_DATES',
  POST_EXPERIENCE: 'POST_EXPERIENCE',
  PUT_EXPERIENCE: 'PUT_EXPERIENCE',
  GET_IMAGES: 'GET_IMAGES',
  IMAGE_UPLOAD_RESET: 'IMAGE_UPLOAD_RESET',
  IMAGE_UPLOAD_START: 'IMAGE_UPLOAD_START',
  IMAGE_UPLOAD_COMPLETE: 'IMAGE_UPLOAD_COMPLETE',
};
