export default {
  GET_EXPERIENCE_DETAILS: 'GET_EXPERIENCE_DETAILS',
  GET_EXPERIENCES: 'GET_EXPERIENCES',
  GET_IMAGES: 'GET_IMAGES',
  IMAGE_UPLOAD_RESET: 'IMAGE_UPLOAD_RESET',
  IMAGE_UPLOAD_START: 'IMAGE_UPLOAD_START',
  IMAGE_UPLOAD_COMPLETE: 'IMAGE_UPLOAD_COMPLETE',
};
