const { resolve } = require('path');

module.exports = [
  {
    "ID": "1",
    "Activity": "Fishing",
    "Occupation": "Commercial Fisherman",
    "City": "Tokyo",
    "Country": "Japan",
    "Price": "150",
    "Guests": "5",
    "Date": "2019-01-17",
    "Host Name": "Sakuragi Hanamichi",
    "Host_Info": "Sakuragi comes from a long line of commercial fisherman in Japan and has been fishing for over 25 years. Fishing is his livelihood and passion.",
    "Activity_Info": "Meet at the dock at 4am. Load up the boat and head out to the fishing grounds. Fish until the holds are full or the light goes down. Head back to the dock and unload the catch. Clean the boat and call it a day.",
    "Image_Url": resolve('images') + '\\fishing.jpg',
  },
  {
    "ID": "2",
    "Activity": "Manual Labor",
    "Occupation": "Ranch Hand",
    "City": "Corpus Christi, Texas",
    "Country": "U.S.",
    "Price": "250",
    "Guests": "10",
    "Date": "2019-01-09",
    "Host Name": "Burnett Ranches",
    "Host_Info": "Currently owned by Anne Marion, the great-granddaughter of the four sixes hunting ranch founder Samuel Burnett, the Burnett ranches have been operational since 1868. The ranch has two locations, one in Guthrie and one in the panhandle, and the family breeds horses and black Angus cattle.",
    "Activity_Info": "Meet at the stable at 6am. Shovel out the horse stables. Put fresh hay in the stables.  Lunch at noon.  Feed the animals.  General manual labor",
    "Image_Url": resolve('images') + '\\ranch.jpg',
  },
  {
    "ID": "3",
    "Activity": "Stock Trading",
    "Occupation": "NYSE Floor Broker",
    "City": "Manhattan, NY",
    "Country": "U.S.",
    "Price": "300",
    "Guests": "2",
    "Date": "2019-09-12",
    "Host Name": "Patrick Bateman",
    "Host_Info": "I have been a floor trader on Wall Street for 5 years.  I consider myself to be the eyes and ears for my clients and their portfolios.",
    "Activity_Info": "Meet outside the NYSE building at 8, grab some coffee.  Hit the floor of the exchange by 9am. opening bell is rung at 930am and closing bell is at 4pm.  We stay on the floor the whole time, except to use the restroom.",
    "Image_Url": resolve('images') + '\\trading.jpg',
  },
  {
    "ID": "4",
    "Activity": "Making Sushi",
    "Occupation": "Itamae (Sushi Chef)",
    "City": "Ginza, Tokyo",
    "Country": "Japan",
    "Price": "200",
    "Guests": "3",
    "Date": "2019-02-02",
    "Host Name": "Jiro Ono",
    "Host_Info": "Jiro Ono is a Japanese chef and owner of Sukiyabashi Jiro, a three-Michelin-starred Japanese sushi restaurant. Ono has been regarded by his contemporaries and peers as the greatest sushi craftsman alive and is credited with innovating methods used in modern sushi preparation.",
    "Activity_Info": "Preparation of sushi rice, sharpening sushi knives. Preparing blocks of fish, grating ginger and slicing scallions.",
    "Image_Url": resolve('images') + '\\sushi.jpg',
  },
  {
    "ID": "5",
    "Activity": "Driving around London",
    "Occupation": "London Black Cab Driver",
    "City": "London",
    "Country": "England",
    "Price": "100",
    "Guests": "4",
    "Date": "2019-02-12",
    "Host Name": "Oliver Williams",
    "Host_Info": "Oliver has been a London Black Cab Driver for 25 years.  He knows the city like the back of his hand since the cabby examination is possibly the most difficult test in the world \u2014 demanding years of study to memorize the labyrinthine city\u2019s 25,000 streets and any business or landmark on them.",
    "Activity_Info": "We will be driving around in the cab picking up fares from 6am until 8pm, breaking for lunch and dinner when we have time.  You will get to experience the city and I will provide historical info on all landmarks as we drive around.",
    "Image_Url": resolve('images') + '\\taxi.jpg',
  }
];
